### ISSUE TITLE
Getting HTBAC running on Titan

### ISSUE THREAD

**Issue by jdakka** [radical-cybertools/htbac#1]
Currently blocked by: 

- [Ticket 1568](https://github.com/radical-cybertools/radical.pilot/issues/1568)
- [Ticket 1567](https://github.com/radical-cybertools/radical.pilot/issues/1567)
- [Ticket 1566](https://github.com/radical-cybertools/radical.pilot/issues/1560)
- [Ticket 214](https://github.com/radical-cybertools/radical.entk/issues/214)

**Comment by kristofarkas** [comment]
It looks like `aprun` might be limited to 13 concurrent tasks (pending ticket). Otherwise, running a local RMQ solves the other problems.

Long term solution is to compile NAMD with internal openMP and run using ORTE.

**Comment by jdakka** [comment]
Long term solution is to compile NAMD with internal openMP and run using ORTE.
- Not necessarily, we can still run NAMD with ORTE, however we can only make use of hyper-threading i.e. each NAMD call can only use up-to 1 node. While this means that we cannot scale the nodes to 300+ node jobs to overcome runtime limitations, can we scale the number of mutations to reach >300 nodes?

**Comment by kristofarkas** [comment]
We want single `namd` executables to run on 1 node only. And yes, we have more than enough mutations to scale to 300+ nodes.

**Comment by mturilli** [comment]
Has anyone tested NAMD on single node with ORTE?

**Comment by jdakka** [comment]
Testing today now that I'm not blocked by [1568](https://github.com/radical-cybertools/radical.pilot/issues/1568)

**Comment by jdakka** [comment]
Installed local RMQ on Titan (before @vivek-bala created the open shift RMQ) as per ticket [214](https://github.com/radical-cybertools/radical.entk/issues/214#issuecomment-369049118)

`ORTE` fails on Titan: **I am blocked by ticket** [1572](https://github.com/radical-cybertools/radical.pilot/issues/1572)

**Comment by jdakka** [comment]
** Update: still blocked by ticket [1572](https://github.com/radical-cybertools/radical.pilot/issues/1572#issuecomment-369303603)

Waiting on @andre-merzky to merge branches before fruitful testing.

**Comment by jdakka** [comment]
Update: `RADICAL-Pilot` works with `ORTE`. Setting up correct OS variables for `namd2` executable. Will have testing complete by EOB.

**Comment by kristofarkas** [comment]
Resurrecting this issue: we need to get TIES working Titan. This means multi-node NAMD runs just on the CPUs (around 8 nodes per TIES replica).

**Comment by kristofarkas** [comment]
Due to the relatively large node count per replica we could attempt an `aprun` approach.

**Comment by kristofarkas** [comment]
@andre-merzky when you compiled NAMD for oRTE, what changes have you made to the normal compiling procedure?

**Comment by kristofarkas** [comment]
@andre-merzky I managed to compile a version of NAMD for titan that works on multiple nodes on CPU only. When I set the core count of the EnTK task to let's say 128, I would expect the `aprun`call to have `-n 8 namd2 ...`, but instead it has the core count `-n 128 namd2`. This must be some minor setting in rp, but I'm not sure where to look.

**Comment by kristofarkas** [comment]
With the new api in EnTK 0.7 I was able to set these values correctly. It seems to be working on Titan. I'll close this (once and for all 🤞🏻).
