### ISSUE TITLE
API change heads up -- ResourceManager is not going to be exposed to be user

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/htbac#14]
So far you have been creating a ResourceManager and assigned it to the AppManager:
```
res_dict = {
            'resource': 'local.localhost',
            'walltime': 5,
            'cores': 1,
            'project': ''
    }
rmgr = ResourceManager(res_dict)
amgr = AppManager()
amgr.resource_manager = rmgr
```

Next release onwards, you only have to assign the res_dict to the AppManager:
```
res_dict = {
            'resource': 'local.localhost',
            'walltime': 5,
            'cores': 1,
            'project': ''
    }
appman = AppManager()
appman.resource_desc = res_dict
```

We are moving towards scenarios where EnTK may be coupled with other runtime systems.
The above changes are to remove the user from having to create a ResourceManager 
depending on the runtime system. The runtime system choice will be an argument or a (new) config 
file parameter.

The release is scheduled for tmrw, but will keep it back compatible so that none of your
current work is effected. I will be capturing the changes in detail in the changelog in EnTK (or in the issues referenced in the changelog).

**Comment by kristofarkas** [comment]
Has this change gone into effect? Which branch?

**Comment by kristofarkas** [comment]
@vivek-bala the `gpu` branch and the changes to the task resource api that come with it are still a separate branch? When is that going to be merged to master?

**Comment by kristofarkas** [comment]
What is the mechanism to set the `shared_data` now that rman is gone?

**Comment by vivek-bala** [comment]
Hey Kristof, the merged branches are in devel. Currently, I am working on improving testing and documentation. This is planned to be released on July 03.

**Comment by kristofarkas** [comment]
@vivek-bala I see the update is out, looks great! I was trying to find documentation on how to set the `shared_data` attribute now that rman is not exposed, but couldn't find it. Do I have to access the private attribute of appman to get rman then set the `shared_data` there?

**Comment by vivek-bala** [comment]
Hey Kristof! The shared_data attribute is moved to the AppManager object now. You are correct in that it needs to be documented. For now, I have added it to changelog. 

Will add it in the next point release (https://github.com/radical-cybertools/radical.entk/issues/247)

**Comment by kristofarkas** [comment]
`shared_data` doesn't seem to be an attribute of `AppManager`. Is this change not merged to the master branch? [search result](https://github.com/radical-cybertools/radical.entk/search?q=shared_data&unscoped_q=shared_data)

**Comment by vivek-bala** [comment]
Thanks for catching that! You are right. I have added it back into the AppManager in master. Docs and tests are updated as well. Waiting for the CI tests to finish, will make a point release in a few mins.

**Comment by kristofarkas** [comment]
Implemented.
