### ISSUE TITLE
ssh instability

### ISSUE THREAD

**Issue by jdakka** [radical-cybertools/htbac#21]
Issue: UCL faces ssh instability when submitting jobs from a local VM (at UCL) to Blue Waters. 

* What is the specs of the UCL VM? 
* How do the specs on the UCL VM compare with the RADICAL-VM2 ? 
* How many users are concurrently submitting jobs to Blue Waters? 
* Are there network issues with the UCL VM? 

@andre-merzky can we get the specifications of the RADICAL-VM in terms of cores, RAM, number of users.

**Comment by mturilli** [comment]
On a separate note, is the user able to quantify this 'instability'?

**Comment by andre-merzky** [comment]
Thanks Matteo!

I agree with the point: `Please note that this specs have little relevance in connection to the stability of ssh connection.`  As long as the system load does not lead to significant stalls which would let the connection time out, the machine seatup and load should have no relevance wrt. to ssh stability.

**Comment by jdakka** [comment]
* The ssh tunnel does not depend on the VM
* UCL wants to run jobs for > 24 hours, what is the upper bound on the duration of UCL's jobs?
* BW is being decommissioned 
* Redirect ticket to [18](https://github.com/radical-cybertools/htbac/issues/18)
