### ISSUE TITLE
place htbac code in radical-cybertools: htbac repo

### ISSUE THREAD

**Issue by shantenujha** [radical-cybertools/htbac#4]
Currently, I don't see htbac code here, and installation instructions point to personal git repo.

_virtualenv $HOME/venv
source $HOME/venv/bin/activate
git clone git@github.com:jdakka/radical.htbac.git_

**Comment by jdakka** [comment]
The htbac code is already here and it's formatted like the other RCT code. The `src` code is available in `/src/radical/htbac`. I've updated the `README` to reflect the correct repo. Thanks for catching that.
