### ISSUE TITLE
Append .json resource config with additional parameters

### ISSUE THREAD

**Issue by jdakka** [radical-cybertools/htbac#6]
## TODO:

- parse `NAMD` executable down to the protocol method along with the appropriate `resource` 
- `if resource == ornl.titan` add in `os` variables 
- update `README` to reflect additional changes to the `API` 
- ORNL specific: update `README` on where to run, where to create `venv`, etc.

**Comment by kristofarkas** [comment]
Moved to [resources.yaml](https://github.com/radical-cybertools/htbac/blob/master/htbac/resources.yaml).
