### ISSUE TITLE
Raise level of abstraction to Protocol()

### ISSUE THREAD

**Issue by jdakka** [radical-cybertools/htbac#7]
- `devel` branch contains pending development

**Comment by jdakka** [comment]
Pushed more changes to `devel`: each Protocol() call can still take on as many systems for a protocol type (Esmacs/Ties). Each call to Protocol() generates a new EnTK pipeline. 

- Need to update `htbac.py` class 
- Need to modify API examples
- Add `.json` to capture differences between Blue Waters and Titan

**Comment by kristofarkas** [comment]
The current protocol abstraction is confusing and not flexible enough. I propose we go back to protocols having steps like minimisation, equilibrate, production, heating, with constrained and unconstrained variants, plus something like recommended numsteps and testing numsteps, encapsulated in a ProtocolStep object for example.
